version: '3'

services:
  fastapi_server:
    build:
      context: ./shrillecho-fastapi
      dockerfile: Dockerfile.server
    container_name: fastapi_server
    volumes:
      - ./shrillecho-fastapi:/app
    ports:
      - "8001:8001"
    expose:
      - 8001
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  next_web:
    build:
      context: ./shrillecho-nextjs
      dockerfile: Dockerfile.web
    volumes:
      - ./shrillecho-nextjs:/app
      - /app/node_modules
      - /app/.next
    container_name: next_web
    ports:
      - "3000:3000"
    expose:
      - 3000
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"